### ISSUE TITLE
npm3 build failed

### ISSUE THREAD

**Issue by yuchuan1** [ddsol/mp3-duration#3]
Using suspend version 0.6.1 results in npm3 build fail.
Please update it to 0.7.0

    Error: Cannot find module '../node_modules/promise/lib/es6-extensions'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

**Comment by ddsol** [comment]
I thought I had. Oops. Also, the tests are not accurate due to bad formula. Fixing...
